### ISSUE TITLE
Pixi 5 support

### ISSUE THREAD

**Issue by PByH** [pixijs/pixi-picture#12]
Hello!
This lib works perfectly with Pixi 4, but doesn't work with Pixi 5.
Is there some plans about adding Pixi 5 compatibility?
Thanks a lot!

**Comment by ivanpopelyshev** [comment]
I have like 10 official plugins for PixiJS. Release is totally random , slightly affected by people who ask for me to push in certain direction ;)

Btw, why do you use it?

Theoretically, I can move it to v5 very fast, in a day. v5 has special features that'll make it much easier.

**Comment by PByH** [comment]
Wow, that sounds great! Thanks for such a quick answer!
I use OVERLAY blend mode in my app to add some ligting: it allows me to use just one lighting texture for different backgrounds, so for me it's a great memory-saving lifehack :) I'd much appreciate if you could do this Pixi 5 compatibility upgrade!

**Comment by lancety** [comment]
hi @ivanpopelyshev , I read lots of your comments about different pixijs questions.  Real appriciate for your hard work.  I am one of the developers who really need the plugin suport of these blend mode. 

In past 2 days I tried to just modify and add the logic in PictureRender and the shader templates into my project as a custom filter, but there are lots change between v4 v5, which I cannot handle them based on my pixi knowledge level. 

Thanks again, and hope we can priorities this plugin migration to v5.  :)

**Comment by ivanpopelyshev** [comment]
ok, then , ill try to do it tomorrow :)

**Comment by ivanpopelyshev** [comment]
Make sure you'll read sources when i do that to understand how its done, because i'll need your and other people opinions to make better documentation later :)

**Comment by lancety** [comment]
Morning @ivanpopelyshev , thanks for your quick response. I am so suprised you can work on this now. You are so amazing :D    

Since I am far to your level about documenting, there is not really much I can say about ways to improve those documents. But if I found anything I can share my opinion surely will let you know.   

I had several years front end developer experience, thought about making web game with pixi for several years :) , just started working on this project last year, build the site skeleton first https://www.galaxy108.online, 

here is what I made so far about the game.  https://www.galaxy108.online/game/index.html   

really appriciate all your work to make my dream possible!!

**Comment by lancety** [comment]
currently the site blocks all link from other sites, so need to refreash if you see a text message said blocked access

**Comment by ivanpopelyshev** [comment]
Yep, im here, working on it

**Comment by ivanpopelyshev** [comment]
Yep, I see that map

**Comment by ivanpopelyshev** [comment]
Too tired, will continue tomorrow

**Comment by lancety** [comment]
hi @ivanpopelyshev, hope you had a lovely week in past days. Just want to check how is this plugin going.   I was working during week days and had no much time to work on my project, but recently I am trying web workers to process map regions' calculation at background.   

Last weekend did not get time to write updates about the blendmode thing I used for map shadow. I used 2 graphics layer one blendmode is substract to make shadow part darker, another one is add to make another side lighter than map regions default color.   Does overlay blendmode make similar result?  I dont have much knowledge about graphic things~ :)

**Comment by ivanpopelyshev** [comment]
Work in progress :)

Yes, but overlay is better. Those formulas dont have much sense to me, but they show good results for artists!

**Comment by Seidi** [comment]
@ivanpopelyshev, Есть новости?

**Comment by PByH** [comment]
> Work in progress :)
> 
> Yes, but overlay is better. Those formulas dont have much sense to me, but they show good results for artists!

Hello, Ivan,

Sorry for bothering, but ... is there any chance, that you finish in, may be, a week or two?
Thank you for spending time on this task. I'm sure, that many peope are grateful for that.

**Comment by ivanpopelyshev** [comment]
Yes :)

**Comment by bigbadwofl** [comment]
Just adding my voice here. Also very interested in using overlay blending with v5 again :)

Thanks for all the effort you put in @ivanpopelyshev

**Comment by ivanpopelyshev** [comment]
Its done!

Look in master branch.

Unfortunately, I had to cut corners and do everything through filters, so there's one small extra pass of framebuffer. I'll make better implementation later.

please remove following line from your apps: `sprite.pluginName='picture'` , and look in README and example.

**Comment by ivanpopelyshev** [comment]
@bigbadwofl @PByH @lancety

**Comment by PByH** [comment]
Wow, thank you so much, Ivan!
For me it works perfectly (tried via .filters). You've done amazing job) Really appreciate this.

**Comment by bigbadwofl** [comment]
Thanks man, this is great.

Will let you know this weekend once I've tried it out.

**Comment by lancety** [comment]
Thank you @ivanpopelyshev , I will try this filter tomorrow and give feedback.  Thank you soooo much~~~  :)

**Comment by lancety** [comment]
hi @ivanpopelyshev ,  I just tried this plugin.  
**First** - I use @types/pixi.js,   pixi.js 5.3.3, pixi-picture plugin,  when I use `import * as PIXIPicture from "pixi-picture", it shows me something unexpected syntex "="`, I guess it was because the dist/pixi-picture.js does not export any module or maybe the types defined in the sibling d.ts file does not have right module that my IDE can detected (webstorm)

**Then** I directly copied the bundle from this repo's dist folder. 

**Second** - with the bundle js, the browser shows an error message at below code,  I changed the blends.XXXXX_PART from text with "\n" to pure string
`
 if (!gl.getShaderParameter(glFragShader, gl.COMPILE_STATUS)) {
            console.warn(fragmentSrc);
            console.error(gl.getShaderInfoLog(glFragShader));
        }
        console.error('Pixi.js Error: Could not initialize shader.');
        console.error('gl.VALIDATE_STATUS', gl.getProgramParameter(program, gl.VALIDATE_STATUS));
        console.error('gl.getError()', gl.getError());
`
the "getShaderInfoLog" generated error 
`ERROR: 0:3: 'constying' : syntax error`

**But** finnally by changing the PART text to pure text quoted by " ` " without "\n", it works.

**Third** - I used below code, it shows very dark output, which is similar to removing the "filters" and "filterArea" in https://pixijs.io/examples/#/plugin-picture/overlay.js.  I am not sure what is wrong.
`
    const texture = PIXI.Texture.from('/game/img/story/landingShip.png');
    const graphicsDarker = new (PIXI as any).picture.Sprite(texture);
    graphicsDarker.name = "mapLighting_darker";
    graphicsDarker.blendMode = PIXI.BLEND_MODES.SOFT_LIGHT;

    container.addChild(graphicsDarker);
    container.filters = [new PIXI.filters.AlphaFilter()];
    container.filterArea = pixiGlobal.renderer.screen;
`

I tried in the https://pixijs.io/examples/#/plugin-picture/overlay.js page, moving all dude to a container, and set filters & filterArea to container, add the container to staging. which looks fine.   My real project code have several level of nested normal container,  as show in "third" part, I tried make a Sprite from image exture, or generated graphics. both gives very dark result, there is no transparent effect.

Do you think there was any specific thing I forget?  From my understanding - I need to set AlphaFilter and filterArea in parent container, and set blend mod in picture Sprite instance.  Should that be all changes to make a sprite have special blend result?
Thanks for your help.

**Comment by lancety** [comment]
Hi @ivanpopelyshev , I tried directly add the sprite to stage object, which works.  wondering why it is not working in a nested container :( (I mean my special nested container, not blaming this plugin is not working , hehe :) )

**Comment by lancety** [comment]
Another question, with picture sprite + texture image, the result looks same as demo.  but when I am using graphics, and set filter as picture.getBlendFilter. the result does not looks like right.

`
const graphicsDarker = new Graphics();
    graphicsDarker.scale.x = csService.terrainViewState.meshScale.val[0];
    graphicsDarker.scale.y = csService.terrainViewState.meshScale.val[1];
    graphicsDarker.name = "mapLighting_darker";
    graphicsDarker.filters=[(PIXI as any).picture.getBlendFilter(PIXI.BLEND_MODES.SOFT_LIGHT)];
    makeLight(map, graphicsDarker);   -> this generates lots of triangles with deffrent level of white to black color.

    pixiGlobal.stage.addChild(graphicsDarker);
    pixiGlobal.stage.filters = [new PIXI.filters.AlphaFilter()];
    pixiGlobal.stage.filterArea = pixiGlobal.renderer.screen;
` 


Will this work ? I am trying this way because the github readme file said - 
`
Assigning a filter to component directly container.filters = [PIXI.picture.getBlendFilter(blendMode)] should work too.
`

**Comment by lancety** [comment]
hi @ivanpopelyshev , I guess the "Graphics" way is working as well, just my expectation of its output is different to what the soft-light really means. 

I was expecting the lighter part can be totally transparent, darker part can be enhanced so it looks like mountain shadow side. Should I use lightness channel of hsl color to make dark level darker, and light side value lighter?  do you have suggestion about any proper way to handle this?  

Thanks for your work. If the part 1 and 2 of my first post today does sound like issue and you need more detail , please @ me here. Cheers~~

**Comment by lancety** [comment]
Also I still have issue about where and how to properly set the parent container's filters and fitlerArea.  I might made some setting in higher level parent which made the plugin not working properly, but not sure what it is.

**Comment by ivanpopelyshev** [comment]
> Hi @ivanpopelyshev , I tried directly add the sprite to stage object, which works. wondering why it is not working in a nested container :( (I mean my special nested container, not blaming this plugin is not working , hehe :) )

I dont know what could you do to stop it from working. it should work in nested containers.

So, again, I and not the one who's using webpack/rollup/any-es6-modules. All my plugins were supposed to work as <script src = 'myplugin.js'/>, without any bundlers. With bundlers and babel its bad. Fortunately, @SukantPal is helping me to move my plugins to UMD + EMS builds, I like his work with pixi-tilemap.

The only requirement to use blending modes & blending filters is : **there has to be a parent container somewhere above that has any filter.** That means `pushFilter` was called and all inner content is rendered to **custom framebuffer** not to **main framebuffer**

If you have an example where it breaks, please make minimal demo and I'll investigate why it doesnt work, because it can be my bug.

**Comment by lancety** [comment]
hi @ivanpopelyshev   I just had another try about making the map terrain shadow by using this plugin and finally made the result I was dreaming to have.  So want to share my happyness and say thank you again for your help. Here is the result screenshot, I used hard light instead of soft light which I tried previously.

![g108](https://user-images.githubusercontent.com/5547558/97849577-db5aa880-1d46-11eb-95e8-fd266c4c5920.PNG)

**Comment by ivanpopelyshev** [comment]
Wow that looks good!
Thank you!

**Comment by lancety** [comment]
hi @ivanpopelyshev ,  I finally moved the shadow calculation to shader in mesh.  Not sure if I am doing it the right way which I will explain below. First want to give feedback about the vertex shader guide improvement. 

Shader guide:
I have no knowledge about glsl, after reading "the book of shaders" I got basic understanding about fregment shader. But no idea what vertex shader is doing, and how it works - such as how to pass in vertexes, until I noticed https://pixijs.io/examples/#/mesh-and-shaders/interleaving-geometry.js is exactly demoing it (which I briefly viewed many times beofre but did not notice it is passing data to "vertex shader").   
Do we have tutorial explains ways to use pixi component to modify vertex shader such as geometry?  **It will be more obvious to mention "vertex shader" when talking about components such as Geometry, it will more easily get glsl beginner's attention (like me, lol)**

How I implemented the hill shading 
1. used geometry + shader in mesh
2. passed in each triangle and their elevation as Geometry attribute (there are about 130k float typedarray and 56k triangle indexes),  
3. passed in sun light direction which also control the global light for morning evening and night.
4. add mesh to light container,
5. add HARD_LIGHT blend mode using pick-picture to the light container.
Please let me know if this is not best way to generate light shadow and render on stage. Cheers~

this git has been compressed lot, the light animation is very smooth even on mobile
![ezgif com-gif-maker (2)](https://user-images.githubusercontent.com/5547558/98300331-43421500-200d-11eb-9779-33fb0d197e0d.gif)
