### ISSUE TITLE
Blend modes are not working.

### ISSUE THREAD

**Issue by a-c-sreedhar-reddy** [pixijs/pixi-picture#18]
Hi.

Tried to use pixi-picture for blendmodes. Blend modes supported by PIXI are working fine. But when I try **hard-light** it does not work.
```
pixijs : 6.0.4
@pixi/picture : 3.0.0
```

## CodeSandbox : https://codesandbox.io/s/inspiring-mendel-x71p1?file=/package.json
<img width="797" alt="Screenshot 2021-06-01 at 3 56 38 PM" src="https://user-images.githubusercontent.com/16081083/120308637-f5b32f80-c2f1-11eb-8911-c983fd6c192c.png">

## Expected (used https://ilyashubin.github.io/FilterBlend/): 
<img width="425" alt="Screenshot 2021-06-01 at 3 55 58 PM" src="https://user-images.githubusercontent.com/16081083/120308575-dddbab80-c2f1-11eb-8258-bb69ef0b1743.png">

**Comment by ivanpopelyshev** [comment]
oh, interesting, i bucked up somewhere

**Comment by ivanpopelyshev** [comment]
OK, here it works: https://codesandbox.io/s/keen-bash-crml5?file=/src/index.js

switch "forceCanvas:true" to see that result is same as canvas. Maybe there's something with transparency in your case?

Main problem was that `pixi-picture` blends work only if there's a filter above it, or you render to renderTexture. This limitation i will remove a bit later. Yes, it hurts performance a bit and turns off antialias if you use it. I'll make it work with "transparent:true" setting of renderer which is default for v6, basically because i need RGBA and not RGB on backdrop surface.

Second (easy) problem is that `Sprite.from` still returns `PIXI.Sprite`, and you tried to solve it by `getBlendFilter`, it could work if not the first issue.

**Comment by ivanpopelyshev** [comment]
Btw you could see `pixi-picture: you are trying to use Blend Filter on main framebuffer! That wont work. ` msg in console :) OK, im going to remove that limitation right now, and release 3.0.1

**Comment by ivanpopelyshev** [comment]
Done, release `3.0.1` does not need background filter
